### PR TITLE
Open CORS to allow front end connection

### LINKED ISSUE #54: Add CORS
Frontend app can't make requests without CORS controls in our Flask app. https://flask-cors.readthedocs.io/en/latest/ looks like a good quick solution but we need to find something.

### PR DESCRIPTION
**Pull request by rhantak**
- Added CORS package to allow the Frontend app to make requests

Closes #54

### CODE REVIEW

**Comment by JamesRexMiller4** [comment]
Going to hold off on the merge until the checks passed

**Comment by rhantak** [comment]
Made a mistake and froze the wrong requirements to the file, waiting to see if I was able to fix it...

**Comment by rhantak** [comment]
Looks like yes @JamesRexMiller4

**Review by grwthomps — APPROVED** [review]
Wow this was simple!

**Comment by rhantak** [comment]
Now that it's set up, once it builds in production, y'all should be able to hit the endpoints without having to do anything weird. Let me or @grwthomps  know if we need to make any adjustments to the CORS! @JamesRexMiller4

**Comment by JamesRexMiller4** [comment]
Very nice! Thanks for getting the cors implemented!

**Pull request merged**
