### PR TITLE
POST ideas endpoint functional

### LINKED ISSUE #19: POST ideas endpoint
Endpoint for saving a user's final idea. Does not include random ideas from games.

Sample request:
```
POST /api/v1/ideas

Body:

{
action: "create an app",
category: ["technology", "education"],
user_response: "this is my idea...",
random_refresh_word: "journey"
}
```

Sample Response:
```
Body:

{
success: "You have successfully saved X idea from this brainstorm." 
}
```

### PR DESCRIPTION
**Pull request by grwthomps**
### What's this PR do?
- Remove `user_id` requirement on Action model to allow for default actions
- Adds new `POST /ideas` route that does the following:
   - Validates user exists in db
   - Validates user idea is NOT already in db
   - Retrieves idea information from request and saves to db

### Where should the reviewer start?
- Make sure to re-migrate and upgrade the database
- Small change to Action model in models.py
- New route in `/app/__init__.py` for `/ideas`

### How should this be manually tested?
- Using Postman or browser, send requests to `POST /ideas` with body formatted as such:
```
{ 
	"user_response": "Full user idea description goes here", 
	"random_word": "Hurricane", 
	"token": "64c153ee2bf6d0b391d54104892ceb49", 
	"action": "Create an App", 
	"isGenuis": "False", 
	"question": "User provided question goes here" ,
        "categories": [{"name": "education"}, {"name": "technology"}]
}
```

closes #19

### CODE REVIEW

**Comment by rhantak** [comment]
I think we're missing categories in here

**Comment by rhantak** [comment]
On a related note, you can check out the dashboard test to see how to append categories to ideas, it'll automatically create the entry in the joins table

**Comment by grwthomps** [comment]
> I think we're missing categories in here

Good catch! Pushing up changes now

**Comment by rhantak** [comment]
Very strange that append wasn't working in the loop, maybe we should just stick with the insert statement moving forward.

**Pull request merged**
